
CREATE DATABASE IF NOT EXISTS ROAD_SAFETY;

CREATE SCHEMA IF NOT EXISTS ROAD_SAFETY.RAW;        -- S3/Glue 
CREATE SCHEMA IF NOT EXISTS ROAD_SAFETY.DBT_DEV;    -- dbt staging + intermediate
CREATE SCHEMA IF NOT EXISTS ROAD_SAFETY.ANALYTICS;  -- marts

-- warehouse 
CREATE WAREHOUSE IF NOT EXISTS KENYA_ANALYTICS_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND   = 60
    AUTO_RESUME    = TRUE;

USE WAREHOUSE KENYA_ANALYTICS_WH;
USE DATABASE   ROAD_SAFETY;
USE SCHEMA     RAW;


-- RAW tables

CREATE OR REPLACE TABLE RAW.ANNUAL_FATALITIES (
    YEAR                INTEGER        NOT NULL,
    TOTAL_FATALITIES    INTEGER,
    TOTAL_ACCIDENTS     INTEGER,
    SERIOUS_INJURIES    INTEGER,
    SLIGHT_INJURIES     INTEGER,
    DATA_SOURCE         VARCHAR(300),
    LOADED_AT           TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.ROAD_USER_FATALITIES (
    YEAR                INTEGER        NOT NULL,
    PEDESTRIANS         INTEGER,
    MOTORCYCLISTS       INTEGER,
    PILLION_PASSENGERS  INTEGER,
    PASSENGERS          INTEGER,
    DRIVERS             INTEGER,
    PEDAL_CYCLISTS      INTEGER,
    LOADED_AT           TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.ACCIDENT_CAUSES (
    CAUSE               VARCHAR(200)   NOT NULL,
    INCIDENTS_2023      INTEGER,
    INCIDENTS_2022      INTEGER,
    CATEGORY            VARCHAR(100),
    LOADED_AT           TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.MONTHLY_FATALITIES (
    MONTH               VARCHAR(20)    NOT NULL,
    MONTH_NUM           INTEGER        NOT NULL,
    FATALITIES_2024     INTEGER,
    FATALITIES_2023     INTEGER,
    LOADED_AT           TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.HOTSPOT_ROADS (
    ROAD_NAME           VARCHAR(200)   NOT NULL,
    REGION              VARCHAR(100),
    ACCIDENTS_2024      INTEGER,
    FATAL_ACCIDENTS_2024 INTEGER,
    LOADED_AT           TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.COUNTY_DATA (
    COUNTY              VARCHAR(100)   NOT NULL,
    ACCIDENTS_2022      INTEGER,
    FATALITIES_2022     INTEGER,
    ACCIDENTS_2023      INTEGER,
    FATALITIES_2023     INTEGER,
    LOADED_AT           TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);
